/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mike Alger (https://sketchfab.com/mikealger)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rigged-t-pose-human-male-w-50-face-blendshapes-cc7e4596bcd145208a6992c757854c07
title: Rigged T-Pose Human Male w 50 Face Blendshapes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/avatar.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.MikeAlger_Material} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['MikeAlger_Material.1']} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials['MikeAlger_Material.2']} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials['MikeAlger_Material.3']} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials['MikeAlger_Material.4']} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials['MikeAlger_Material.5']} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_19.geometry} material={materials['MikeAlger_Material.6']} skeleton={nodes.Object_19.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/avatar.gltf')
